version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: djangotrello
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prediction:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=django-insecure-ez8ot5-*!+2b05esk25#cik^&nl$1-#fi!44&qtrcldv8v8one
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/djangotrello
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - static_volume:/app/static

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - prediction

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:  # Добавить это определение для static_volume
